from toolbox.strings import MarkdownFormat
from toolbox.strings import remove_markdown


def test_remove_markdown():
    assert remove_markdown("", MarkdownFormat.ALL) == ""
    assert remove_markdown("~~a~~", MarkdownFormat.STRIKETHROUGH) == "a"
    assert remove_markdown("||b||", MarkdownFormat.SPOILER) == "b"
    assert remove_markdown("**c**", MarkdownFormat.BOLD) == "c"
    assert remove_markdown("__d__", MarkdownFormat.UNDERLINE) == "d"
    assert remove_markdown("_e_", MarkdownFormat.ITALIC_UNDERSCORE) == "e"
    assert remove_markdown("*f*", MarkdownFormat.ITALIC_ASTERISK) == "f"
    assert remove_markdown("> g", MarkdownFormat.QUOTE) == "g"
    assert remove_markdown(">>> h", MarkdownFormat.MULTI_QUOTE) == "h"
    assert remove_markdown("`i`", MarkdownFormat.CODE_BLOCK) == "i"
    assert remove_markdown("```j```", MarkdownFormat.MULTI_CODE_BLOCK) == "j"
    assert remove_markdown("**~~k~~**", MarkdownFormat.BOLD | MarkdownFormat.STRIKETHROUGH) == "k"
    assert remove_markdown("*_l_*", MarkdownFormat.ITALIC_ASTERISK | MarkdownFormat.ITALIC_UNDERSCORE) == "l"
    assert remove_markdown("~~a~~") == "a"
    assert remove_markdown("||b||") == "b"
    assert remove_markdown("**c**") == "c"
    assert remove_markdown("__d__") == "d"
    assert remove_markdown("_e_") == "e"
    assert remove_markdown("*f*") == "f"
    assert remove_markdown("> g") == "g"
    assert remove_markdown(">>> h") == "h"
    assert remove_markdown("`i`") == "i"
    assert remove_markdown("```j```") == "j"
    assert remove_markdown("**~~k~~**") == "k"
    assert remove_markdown("*_l_*") == "l"
    assert remove_markdown("**__h__**") == "h"
